"""
71858 실데이터에서 '해무 후보' 슬라이스를 만든다 (W8 검증용).

71858엔 해무 등급 라벨이 없다. 대신 meta.weather[6] = 상대습도가 있고,
개방데이터 전수를 보면 습도가 60~99%에 걸쳐 있으며 98% 이상이 40클립/1,837프레임
(3개 날짜 x 4개 지점, 전부 주간)으로 뭉쳐 있다. 이를 해무 후보로 본다.

⚠️ 습도는 대리 지표다. 습해도 시야가 멀쩡할 수 있으므로 뽑은 프레임은
   반드시 육안 또는 이미지 기반 안개 지표로 교차 확인할 것.

왜 필요한가: 합성 해무 데이터로 학습해도 그 효과를 잴 실데이터가 없으면
주장이 성립하지 않는다(야간이 그 상황). 주간 해무는 실데이터가 존재하므로
여기서는 검증이 닫힌다 — 단, 이 클립들을 학습에서 빼야 한다.

출력 (ultralytics 표준, 슬라이스별):
    <out>/images/<slice>/<stem>.jpg
    <out>/labels/<slice>/<stem>.txt
    <out>/<slice>.yaml
"""
import argparse, json, zipfile
from pathlib import Path

CLASS_MAP = {"0": 0, "1": 1, "2": 2}   # 어선/상선/군함. 사람"3"·조류"4" 제외(json_to_yolo와 동일 규약)
NAMES = {0: "fishing_boat", 1: "merchant_ship", 2: "warship"}
HUMIDITY_IDX = 6                       # meta.weather = [기온,풍향,풍속,강수,기압,기압,습도]


def load_labels(label_zip):
    """stem -> (meta, annotations). zip은 평면 구조(§10-3)."""
    zf = zipfile.ZipFile(label_zip)
    out = {}
    for n in zf.namelist():
        if not n.lower().endswith(".json"):
            continue
        try:
            d = json.loads(zf.read(n))
        except (zipfile.BadZipFile, json.JSONDecodeError):
            continue
        out[Path(n.strip("/")).stem] = d
    return out


def to_yolo(d):
    lines = []
    for a in d.get("annotations", []):
        c = CLASS_MAP.get(str(a.get("class")))
        if c is None:
            continue
        W = a.get("width") or 1920
        H = a.get("height") or 1080
        x, y, w, h = a["bbox"]
        cx, cy = (x + w / 2) / W, (y + h / 2) / H
        nw, nh = w / W, h / H
        lines.append(f"{c} {min(max(cx,0),1):.6f} {min(max(cy,0),1):.6f} "
                     f"{min(nw,1):.6f} {min(nh,1):.6f}")
    return lines


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--label-zip", required=True, help="TL_I2_S0_C5.zip")
    ap.add_argument("--image-zip", required=True, help="TS_I2_S0_C5.zip")
    ap.add_argument("--val-clips", required=True, help="splits_*/val_clips.txt")
    ap.add_argument("--out", required=True)
    ap.add_argument("--fog-min", type=float, default=98, help="해무 후보 습도 하한(%%)")
    ap.add_argument("--clear-max", type=float, default=90, help="대조군 습도 상한(%%)")
    args = ap.parse_args()

    val = {ln.strip() for ln in Path(args.val_clips).read_text(encoding="utf-8").split() if ln.strip()}
    labels = load_labels(args.label_zip)
    print(f"라벨 {len(labels)}개 / val 클립 {len(val)}개")

    buckets = {"fog_val": [], "clear_val": []}
    for stem, d in labels.items():
        clip = stem[:-3]
        if clip not in val:
            continue
        w = (d.get("meta") or {}).get("weather") or []
        if len(w) <= HUMIDITY_IDX:
            continue
        h = w[HUMIDITY_IDX]
        if h >= args.fog_min:
            buckets["fog_val"].append(stem)
        elif h <= args.clear_max:
            buckets["clear_val"].append(stem)

    out = Path(args.out)
    zf = zipfile.ZipFile(args.image_zip)
    entries = {Path(n.strip("/")).stem: n for n in zf.namelist() if n.lower().endswith(".jpg")}
    names_block = "\n".join(f"  {i}: {n}" for i, n in sorted(NAMES.items()))

    for slc, stems in buckets.items():
        idir = out / "images" / slc
        ldir = out / "labels" / slc
        idir.mkdir(parents=True, exist_ok=True)
        ldir.mkdir(parents=True, exist_ok=True)
        n_box = n_miss = n_bad = 0
        clips = set()
        for stem in sorted(stems):
            src = entries.get(stem)
            if src is None:
                n_miss += 1
                continue
            dst = idir / f"{stem}.jpg"
            if not dst.exists():
                try:
                    dst.write_bytes(zf.read(src))
                except (zipfile.BadZipFile, KeyError):
                    n_bad += 1                     # zip 손상 항목(§10-3)
                    continue
            lines = to_yolo(labels[stem])
            (ldir / f"{stem}.txt").write_text("\n".join(lines), encoding="utf-8")
            n_box += len(lines)
            clips.add(stem[:-3])
        yaml = out / f"{slc}.yaml"
        yaml.write_text(
            f"# auto-generated by build_fog_slice.py -- {slc}\n"
            f"path: {out.resolve()}\n"
            f"train: images/{slc}\n"          # ultralytics 8.4는 val만 해도 train 키를 요구
            f"val: images/{slc}\n\n"
            f"names:\n{names_block}\n", encoding="utf-8")
        print(f"[{slc}] 프레임 {len(stems)-n_miss-n_bad} 박스 {n_box} 클립 {len(clips)} "
              f"(img_missing={n_miss} corrupt={n_bad}) -> {yaml}")


if __name__ == "__main__":
    main()
